sound = 'u';
repeat = 1;
folder = sprintf('Final_Recordings_1/');
newFolder = sprintf('Final_Recordings_angle_reversed/');

for phi = 0:10:360
        
        % Calculate filenames
        azimuth = phi;
        elevation = 0;
        
        normSignalFilename = sprintf('%s_%d_%d_%d_N.wav',...
                                     sound, repeat, azimuth,elevation);
        testSignalFilename = sprintf('%s_%d_%d_%d_T.wav',...
                                     sound, repeat, azimuth,elevation);
        normSignalFilepath = sprintf('%s%s',...
                                     folder, normSignalFilename);
        testSignalFilepath = sprintf('%s%s',...
                                     folder, testSignalFilename);
        
        [normalData, fs] = audioread(normSignalFilepath);
        [testData, fs] = audioread(testSignalFilepath);
        
        new_azimuth = 360 - azimuth;
        
        new_normSignalFilename = sprintf('%s_%d_%d_%d_N.wav',...
                                         sound, repeat,...
                                         new_azimuth,elevation);
        new_testSignalFilename = sprintf('%s_%d_%d_%d_T.wav',...
                                         sound, repeat,...
                                         new_azimuth,elevation);
        new_normSignalFilepath = sprintf('%s%s',...
                                         newFolder,...
                                         new_normSignalFilename);
        new_testSignalFilepath = sprintf('%s%s',...
                                         newFolder,...
                                         new_testSignalFilename);
        
        audiowrite(new_normSignalFilepath, normalData,...
                   fs, 'BitsPerSample', 24);
        audiowrite(new_testSignalFilepath, testData,...
                   fs, 'BitsPerSample', 24);
end